[package]
name = "lib-with-bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-analyzer-use-lib-bug-report = { path = "../", version = "0.1.0" }